### ISSUE TITLE
Salt installation on Pi

### ISSUE THREAD

**Issue by ghost** [davidjb/salt-raspberry-pi#2]
HI there, great repo thanks

I've been using Ansible and Puppet because I read somewhere that it was difficult to get Salt working on ARM

Can you please explain the method you used?

**Comment by davidjb** [comment]
Hi,

I use salt-ssh, which deploys a salt onto the machine directly and then
runs the state configuration (e.g. Highstate). There was no issue doing
that; Salt is mostly just Python scripts so that works fine.

If you wanted to use a different configuration, such as master / minion
etc, you I wouldn't imagine you'd have any issues installing the minion on
the Pi. There's official Raspian packages from the project:
https://docs.saltstack.com/en/latest/topics/installation/debian.html ; if
they're not working, definitely report a bug.

And if you're not using Raspian or if packages aren't available for your
platform, then installing from source is straightforward too.

**Comment by ghost** [comment]
Thanks David, that's basically how Ansible works as well so I might give it a go.

**Comment by davidjb** [comment]
No worries; if any of the states in this repo might help you, fork/use/copy etc and feel free to suggest anything that might also be useful!
